title: DubbleBubble
description: "My name is Alice and I created this blog to help the people use
  the internet to understand what typography is. Since 2008, I have helped
  countless people and now I am going to help you to understand this important
  topic and everything connected with it. "
footer_text: Copyright 2021 DubbleBubble
header_feature_image: ../uploads/muhammad-haikal-sjukri-rmbf_xsf2u-unsplash.jpg
header_text: Typography In The Wild
header_text_color: "#ffffff"
bannerheight: 40vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
